"""
Django settings for depth3 project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/

Created on 06.02.2021

@author: Richard Kunzmann
"""
import environ
from pathlib import Path
from pickle import TRUE
#from corsheaders.middleware import ACCESS_CONTROL_ALLOW_CREDENTIALS

env = environ.Env()
environ.Env.read_env()  # reading .env file


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_DIR = "/home/richard/OpenSeaMap/WebFrontend"         # RKu: Steffen

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

SECRET_KEY = env.str('SECRET_KEY')
ALLOWED_HOSTS = ['*']                                       #RKu: set to '*'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',                                              # RKu:
    'rest_framework',
    'captcha',                                           # RKu:
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
#    'django.middleware.common.CommonMiddleware',            # RKu:
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'corsheaders.middleware.CorsMiddleware',                # RKu: wichtig zuvor sudo pip3 install django-core-headers
    'django.middleware.common.BrokenLinkEmailsMiddleware',  # RKu:
    'django.middleware.common.CommonMiddleware',            # RKu:
]

# CORS_ORIGIN_ALLOW_ALL = True                                # RKu: normal False
# CORS_ORIGIN_WHITELIST = [                                   # RKu: erlaubnis über die whitelist einstellen
CORS_ALLOWED_ORIGINS = [                                    # RKu: neu, ersetzt whitelist
    'http://localhost',
    'http://localhost:8000'
]

CORS_Allow_Credentials = True


ROOT_URLCONF = 'depth3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'depth3.wsgi.application'

# mail account settings
EMAIL_BACKEND = env.str('EMAIL_BACKEND')
EMAIL_HOST =  env.str('EMAIL_HOST')
EMAIL_PORT =  env.str('EMAIL_PORT')
EMAIL_HOST_USER =  env.str('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD =  env.str('EMAIL_HOST_PASSWORD')
EMAIL_USE_SSL = True

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {                           # RKu: setzt die OSM DB als default
    'default': {
        'ENGINE': env.str('DB_ENGINE'),
        'NAME': env.str('DB_NAME'),
        'USER': env.str('DB_USER'),
        'PASSWORD': env.str('DB_PASSWORD'),
        'HOST': env.str('DB_HOST'),
        'PORT': env.str('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'         # RKu: Steffen

STATICFILES_DIRS=[              # RKu: Steffen
    STATIC_DIR,
]

APPEND_SLASH=False


