# Generated by Django 3.1.5 on 2021-02-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depthuser',
            name='last_attempt',
            field=models.DateTimeField(null=True, verbose_name='last time this user attempted or successfully logged in'),
        ),
    ]
