# Generated by Django 3.1.5 on 2021-02-12 20:06

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tracks.indexmanager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vessels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded')),
                ('processing_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('FID', 'Format identified'), ('ING', 'Ingesting'), ('DNE', 'Done')], default='NEW', max_length=3)),
                ('rawfile', models.FileField(upload_to='raw_tracks/')),
                ('format', models.CharField(blank=True, choices=[('GPX', 'Gpx'), ('183', 'NMEA 0183'), ('OSM', 'NMEA 0183 with OSM timestamps'), ('CSV', 'CSV with column headers')], default='', max_length=3)),
                ('fingerprint', models.CharField(blank=True, max_length=64)),
                ('fingerprintmethod', models.CharField(blank=True, choices=[('MD5', 'Md5'), ('SHA256', 'Sha256')], default='', max_length=10)),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name="optional uploaders' note")),
                ('quality', models.IntegerField(default=0, verbose_name='a track quality measure from 0 (unusable) to 100 (perfect)')),
                ('nPoints', models.IntegerField(default=0, null=True, verbose_name='number of points in track')),
                ('license', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenses.license')),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vessels.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Sounding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', django.contrib.gis.db.models.fields.PointField(srid=3857)),
                ('z', models.FloatField()),
                ('min_level', models.PositiveSmallIntegerField(default=18)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
            ],
            bases=(tracks.indexmanager.IndexManagerMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='sounding',
            index=models.Index(fields=['coord'], name='coord_idx', opclasses=['GIST_GEOMETRY_OPS_ND']),
        ),
        migrations.AddIndex(
            model_name='sounding',
            index=models.Index(fields=['min_level'], name='min_level_idx'),
        ),
        migrations.AddIndex(
            model_name='sounding',
            index=models.Index(fields=['track'], name='track_idx'),
        ),
        migrations.AddIndex(
            model_name='sounding',
            index=models.Index(fields=['z'], name='z_idx'),
        ),
    ]
