# Generated by Django 3.1.4 on 2021-01-03 23:55

from django.db import migrations, models
import tracks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=tracks.models.User.now),
        ),
    ]
