# Generated by Django 3.1.5 on 2021-01-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='note',
            field=models.CharField(default='', max_length=200, null=True, verbose_name="optional uploaders' note"),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='depth_sensor_offset_x',
            field=models.FloatField(verbose_name='distance of transducer from stern in meters'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='depth_sensor_offset_y',
            field=models.FloatField(verbose_name='distance of transducer from centerline in meters'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='depth_sensor_offset_z',
            field=models.FloatField(verbose_name='position of transducer below waterline in meters'),
        ),
    ]
