# Generated by Django 3.1.4 on 2021-01-04 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created in database'),
        ),
    ]
