# Generated by Django 3.1.4 on 2021-01-03 23:56

from django.db import migrations, models
import tracks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20210104_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='uploaded_on',
            field=models.DateTimeField(default=tracks.models.now, verbose_name='date uploaded'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='created_on',
            field=models.DateTimeField(default=tracks.models.now, verbose_name='date created in database'),
        ),
    ]
