# Generated by Django 3.1.4 on 2021-01-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20210104_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='depth_sensor_manufacturer',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='depth_sensor_model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='depth_sensor_offset_keel',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vessel',
            name='height',
            field=models.FloatField(null=True, verbose_name='height in meters'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='measurement_type',
            field=models.CharField(choices=[('BT', 'depth below transducer'), ('BK', 'depth below keel'), ('BW', 'depth below waterline')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='processing_status',
            field=models.CharField(choices=[('NEW', 'New'), ('ING', 'Ingesting'), ('DNE', 'Done')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='depth_sensor_offset_x',
            field=models.FloatField(verbose_name='distance from stern in meters'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='depth_sensor_offset_y',
            field=models.FloatField(verbose_name='distance from centerline in meters'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='depth_sensor_offset_z',
            field=models.FloatField(verbose_name='position below waterline in meters'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='gps_sensor_offset_z',
            field=models.FloatField(verbose_name='position above waterline in meters'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vtype',
            field=models.CharField(choices=[('SY', 'Sailing Yacht'), ('MB', 'motorboat (planing hull)'), ('MY', 'Motor Yacht (displacement hull)'), ('RB', 'Rudder Boat'), ('KJ', 'Kajak'), ('DG', 'Dinghy')], max_length=2),
        ),
        migrations.DeleteModel(
            name='ProcessingStatus',
        ),
    ]
