# Generated by Django 3.1.4 on 2021-01-04 00:00

from django.db import migrations, models
import tracks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20210104_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='created_on',
            field=models.DateTimeField(default=tracks.models.Vessel.now, verbose_name='date created in database'),
        ),
    ]
