# Generated by Django 3.1.5 on 2021-01-28 07:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20210126_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounding',
            name='coord',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, srid=3857),
        ),
    ]
