# Generated by Django 3.1.4 on 2021-01-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_auto_20210104_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='note',
            field=models.CharField(max_length=200, null=True, verbose_name="optional uploaders' note"),
        ),
        migrations.AlterField(
            model_name='track',
            name='processing_status',
            field=models.CharField(choices=[('NEW', 'New'), ('ING', 'Ingesting'), ('DNE', 'Done')], default='NEW', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='quality',
            field=models.IntegerField(null=True, verbose_name='a track quality measure from 0 (unusable) to 100 (perfect)'),
        ),
    ]
