# Generated by Django 3.1.5 on 2021-01-28 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20210128_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('processing_progress', models.FloatField(default=0, verbose_name='The operation progress in percent')),
                ('time_left', models.DurationField(null=True, verbose_name='Estimated time left until completion')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time of start of operation')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time of end of operation')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
            ],
        ),
    ]
