# Generated by Django 3.1.4 on 2021-01-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20210104_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='processing_status',
            field=models.CharField(choices=[('NEW', 'New'), ('FID', 'Format identified'), ('ING', 'Ingesting'), ('DNE', 'Done')], default='NEW', max_length=3, null=True),
        ),
    ]
