# Generated by Django 3.1.5 on 2021-01-28 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_processingstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingstatus',
            name='processing_progress',
        ),
        migrations.RemoveField(
            model_name='processingstatus',
            name='time_left',
        ),
        migrations.AddField(
            model_name='processingstatus',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time of last update'),
        ),
        migrations.AddField(
            model_name='processingstatus',
            name='nProcessed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingstatus',
            name='toProcess',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='processingstatus',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='date and time of start of operation'),
        ),
    ]
