# Generated by Django 3.1.4 on 2021-01-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0005_auto_20210105_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='format',
            field=models.CharField(choices=[('GPX', 'Gpx'), ('183', 'NMEA 0183'), ('OSM', 'NMEA 0183 with OSM timestamps')], max_length=3, null=True),
        ),
    ]
