# Generated by Django 3.1.5 on 2021-01-06 22:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0006_track_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPointsSounding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', django.contrib.gis.db.models.fields.LineStringField(dim=3, srid=4326)),
            ],
        ),
    ]
