# Generated by Django 3.1.5 on 2021-01-07 09:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0007_trackpointssounding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackpointssounding',
            name='points',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326),
        ),
    ]
