# Generated by Django 3.1.5 on 2021-01-07 09:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0008_auto_20210107_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sounding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326)),
                ('min_level', models.SmallIntegerField()),
                ('track_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
            ],
        ),
        migrations.DeleteModel(
            name='TrackPointsSounding',
        ),
    ]
