# Generated by Django 3.1.5 on 2021-01-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0009_auto_20210107_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sounding',
            old_name='point',
            new_name='coord',
        ),
        migrations.RenameField(
            model_name='sounding',
            old_name='track_id',
            new_name='track',
        ),
        migrations.AlterField(
            model_name='sounding',
            name='min_level',
            field=models.SmallIntegerField(default=21),
        ),
    ]
