# Generated by Django 3.1.5 on 2021-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_track_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='nPoints',
            field=models.IntegerField(null=True, verbose_name='number of points in track'),
        ),
    ]
