# Generated by Django 3.1.5 on 2021-01-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0010_auto_20210107_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounding',
            name='min_level',
            field=models.PositiveSmallIntegerField(default=21),
        ),
    ]
