# Generated by Django 3.1.5 on 2021-01-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0011_auto_20210107_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounding',
            name='min_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=21),
        ),
        migrations.AlterField(
            model_name='track',
            name='format',
            field=models.CharField(choices=[('UND', 'undetermined'), ('GPX', 'Gpx'), ('183', 'NMEA 0183'), ('OSM', 'NMEA 0183 with OSM timestamps')], default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='note',
            field=models.CharField(default=None, max_length=200, null=True, verbose_name="optional uploaders' note"),
        ),
        migrations.AlterField(
            model_name='track',
            name='quality',
            field=models.IntegerField(default=None, null=True, verbose_name='a track quality measure from 0 (unusable) to 100 (perfect)'),
        ),
    ]
