# Generated by Django 3.1.5 on 2021-02-04 21:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0011_track_npoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sounding',
            name='coord',
            field=django.contrib.gis.db.models.fields.PointField(srid=3857),
        ),
        migrations.AlterField(
            model_name='sounding',
            name='min_level',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='sounding',
            name='z',
            field=models.FloatField(),
        ),
        migrations.AddIndex(
            model_name='sounding',
            index=models.Index(fields=['coord'], name='coord_idx'),
        ),
        migrations.AddIndex(
            model_name='sounding',
            index=models.Index(fields=['min_level'], name='min_level_idx'),
        ),
        migrations.AddIndex(
            model_name='sounding',
            index=models.Index(fields=['track'], name='track_idx'),
        ),
        migrations.AddIndex(
            model_name='sounding',
            index=models.Index(fields=['z'], name='z_idx'),
        ),
    ]
