# Generated by Django 3.1.5 on 2021-02-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0012_auto_20210204_2222'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sounding',
            name='coord_idx',
        ),
        migrations.AddIndex(
            model_name='sounding',
            index=models.Index(fields=['coord'], name='coord_idx', opclasses=['GIST_GEOMETRY_OPS_ND']),
        ),
    ]
