# Generated by Django 3.1.5 on 2021-02-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0013_auto_20210205_0041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessingStatus',
        ),
    ]
