# Generated by Django 3.1.5 on 2021-02-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0014_delete_processingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='nPoints',
            field=models.IntegerField(default=0, verbose_name='number of points in track'),
        ),
    ]
