# Generated by Django 3.1.5 on 2021-02-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0015_auto_20210209_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='nPoints',
            field=models.IntegerField(default=0, null=True, verbose_name='number of points in track'),
        ),
    ]
