# Generated by Django 3.1.5 on 2021-02-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0016_auto_20210209_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='track',
            name='fingerprintmethod',
            field=models.CharField(blank=True, choices=[('MD5', 'Md5'), ('SHA256', 'Sha256')], default='', max_length=10),
        ),
    ]
