# Generated by Django 3.1.5 on 2021-02-02 22:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='the vessel name')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created in database')),
                ('length', models.FloatField(verbose_name='length in meters')),
                ('beam', models.FloatField(verbose_name='beam in meters')),
                ('draft', models.FloatField(verbose_name='draft in meters')),
                ('height', models.FloatField(verbose_name='height in meters')),
                ('displacement', models.FloatField(verbose_name='displacement in metric tons')),
                ('manufacturer', models.CharField(blank=True, max_length=128, verbose_name='the name of the manufacturer')),
                ('model', models.CharField(blank=True, max_length=128, verbose_name='the model/type of vessel as given by the manufacturer')),
                ('vtype', models.CharField(choices=[('SY', 'Sailing Yacht'), ('MB', 'motorboat (planing hull)'), ('MY', 'Motor Yacht (displacement hull)'), ('RB', 'Rudder Boat'), ('KJ', 'Kajak'), ('DG', 'Dinghy')], max_length=2)),
                ('depth_sensor_offset_x', models.FloatField(verbose_name='distance of transducer from stern in meters')),
                ('depth_sensor_offset_y', models.FloatField(verbose_name='distance of transducer from centerline in meters')),
                ('depth_sensor_offset_z', models.FloatField(verbose_name='position of transducer below waterline in meters')),
                ('gps_sensor_offset_x', models.FloatField(verbose_name='lateral offset of GPS sensor in meters')),
                ('gps_sensor_offset_y', models.FloatField(verbose_name='longitudinal offset of GPS sensor in meters')),
                ('gps_sensor_offset_z', models.FloatField(verbose_name='position above waterline in meters')),
                ('measurement_type', models.CharField(choices=[('BT', 'depth below transducer'), ('BK', 'depth below keel'), ('BW', 'depth below waterline')], max_length=2, null=True)),
                ('depth_sensor_offset_keel', models.FloatField(blank=True, null=True)),
                ('depth_sensor_manufacturer', models.CharField(blank=True, default='', max_length=32)),
                ('depth_sensor_model', models.CharField(blank=True, default='', max_length=20)),
                ('submitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.depthuser')),
            ],
        ),
    ]
