# Generated by Django 3.1.5 on 2021-02-02 23:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vessels', '0002_auto_20210202_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date created in database'),
        ),
    ]
