# Generated by Django 3.1.5 on 2021-02-12 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('toProcess', models.IntegerField(null=True)),
                ('nProcessed', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time of start of operation')),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date and time of last update')),
                ('end_time', models.DateTimeField(null=True, verbose_name='date and time of end of operation')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track')),
            ],
            options={
                'verbose_name_plural': 'processing statuses',
                'ordering': ['-last_update'],
            },
        ),
    ]
