# Generated by Django 3.1.5 on 2021-02-06 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='license',
            name='visited_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
